export const ERROR_TYPES = {
  CANT_GET_CONVERSATIONS: 'CANT_GET_CONVERSATIONS',
  CANT_DELETE_CONVERSATION: 'CANT_DELETE_CONVERSATION',
  CANT_GET_MESSAGES: 'CANT_GET_MESSAGES',
  CANT_SEND_MESSAGE: 'CANT_SEND_MESSAGE',
};
